### ISSUE TITLE
Issues with blockstate property injections

### ISSUE THREAD

**Issue by noobanidus** [Ephys/mc-shulker-enchantments#6]
From my discussions with some other Forge developers, injecting properties into vanilla blockstates is a really bad idea. I don't remember the precise reasons (Gigaherz explained it to me at one point), but there are some internal logistics that can be ruined by additional, unexpected.

Just off the top of my head, there's a conflict with the latest version of Lootr which adds support for Shulker boxes, as I don't currently call the `super` in `fillStateContainer` in my ShulkerBoxBlock-derived class, meaning your mixin never applies, but your constructor mixin runs with the assumption that the injection has happened, which then causes a crash upon mod initialization.

At the very least, this is going to be an unreliable method that will potentially introduce further compatibility issues in the future.

For now, I can simply remove my override to `fillStateContainer` as it isn't really needed, but I'd at least recommend extending the sanity-checking you have for the *presence* of the property (that exists in your TileEntityRenderer mixin) to your other mixins to prevent it from happening in the future.

**Comment by noobanidus** [comment]
Further on this, some information from TelepathicGrunt on the significance of mixing new properties in, suggesting the use of the [Statement library](https://www.curseforge.com/minecraft/mc-mods/statement) instead.

> Using a simple mixin to add blockstates will blow up the blockstate codec for worldgen json files. Multiple mods tried this and kept breaking repurposed structures because I use the vanilla worldgen json system. Statement solved this issue and won’t cause said issue with json worldgen files that uses the blockstate codec.

**Comment by ephys** [comment]
Thanks for all this info :)

This property injection is done mostly for making the item use a bakedmodel instead of the tser and display the enchantment glint, with the added benefit that shulkerboxes are displayed further than TSERs.

I'll see how I can support the glint without adding new properties

Lootr looks cool by the way :)

**Comment by ephys** [comment]
Build https://www.curseforge.com/minecraft/mc-mods/shulker-enchantments/files/3536783 should resolve this issue
