### ISSUE TITLE
Add link to new fabric mod

### ISSUE THREAD

**Issue by RubixDev** [Ephys/mc-shulker-enchantments#8]
On the CurseForge page there currently is a link to an old discontinued fabric mod called [BetterShulkers](https://www.curseforge.com/minecraft/mc-mods/fabric-bettershulkers). Over the last week I made a new mod with similar functionality to these two mods called [EnchantedShulkers](https://github.com/RubixDev/EnchantedShulkers), available for fabric 1.18.2 onwards. I think it would make sense to add a link to that on your mod page.

**Comment by ephys** [comment]
EnchantedShulkers is really cool! It has options that are definitely missing from this mod. I spent a lot of time trying to make the glint work without an ugly overlap, did not think to render a cube model in the block entity renderer. Really cool! :) I've added a link to it on the curseforge page.

Do you mind if I steal your idea of applying these enchantments to ender chests as well?

**Comment by RubixDev** [comment]
> I've added a link to it on the curseforge page.

Thanks!

> Do you mind if I steal your idea of applying these enchantments to ender chests as well?

Not at all, go ahead
